# Generated by Django 3.0 on 2019-12-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premlgueapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='draws',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='overview',
            name='goal_difference',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='overview',
            name='goals_conceded',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='overview',
            name='goals_scored',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='overview',
            name='league_position',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='overview',
            name='losses',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='overview',
            name='matches_played',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='overview',
            name='team_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='overview',
            name='wins',
            field=models.IntegerField(),
        ),
    ]
