# Generated by Django 3.0 on 2019-12-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_id', models.CharField(max_length=100)),
                ('player_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=100)),
                ('min_played_home', models.IntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('appearances', models.IntegerField()),
                ('goals_total', models.IntegerField()),
                ('overall_assists', models.IntegerField()),
                ('penalty_goals', models.IntegerField()),
                ('yellow_cards', models.IntegerField()),
                ('red_cards', models.IntegerField()),
            ],
            options={
                'db_table': 'player',
            },
        ),
    ]
