# Generated by Django 3.0 on 2019-12-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plyrstats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team_id',
            field=models.IntegerField(),
        ),
    ]
